name: GitHub Snake

on:
  schedule:
    - cron: '0 0 * * *' # every day at midnight UTC
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Clone Snake Generator via HTTPS
        run: |
          git clone https://github.com/Ashutosh00710/github-contribution-grid-snake.git snake
          cd snake
          npm install
          node index.js -u Dhanush0254

      - name: Move SVG to assets
        run: |
          mkdir -p assets
          mv snake/output/github-contribution-grid-snake.svg ./assets/github-snake.svg

      - name: Commit & push changes
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "actions@github.com"
          git add assets/github-snake.svg
          git commit -m "Update GitHub Snake" || echo "No changes to commit"
          git push
